version: '3'

services:
  unblockneteasemusic:
    image: nondanee/unblockneteasemusic
    build: .
    environment:
      NODE_ENV: production
    entrypoint:
      - node
      - app.js
      - -p
      - "10000"
    ports:
      - 10000:10000